[profile.default]
src = "templates"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC}"
sepolia = "${ETHEREUM_SEPOLIA_RPC}"
bsc = "${BSC_RPC}"
bsc_testnet = "${BSC_TESTNET_RPC}"
polygon = "${POLYGON_RPC}"
mumbai = "${POLYGON_MUMBAI_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
